### PR TITLE
DM-24912: add a test that code is formatted with black. Update .travis.yml

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Comment by r-owen** [comment]
salobj v5.12.0 has that fix: version.py will always be ignored. Can you please mark this as accepted?

BTW: I just added black to the conda test dependencies.

**Comment by tribeiro** [comment]
is salobj v5.12.0 released or merged to develop already?

**Comment by r-owen** [comment]
No. I plan to merge salobj 5.12 as soon as I merge these packages.

**Comment by tribeiro** [comment]
Hold on, let me try something here then...

**Comment by r-owen** [comment]
I just added a temporary tickets/DM-24912 branch to salobj in hopes that Jenkins will use it (then did `git commit --amend` to restart checks for this package).

**Pull request merged**
